# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-05 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluesteelworker', '0004_auto_20160717_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerFilesHashEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files_hash', models.TextField(default=b'')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
