# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-11-24 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluesteelworker', '0005_workerfileshashentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerentry',
            name='description',
            field=models.TextField(default='Edit this description!'),
        ),
        migrations.AlterField(
            model_name='workerentry',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='workerentry',
            name='operative_system',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='workerentry',
            name='uuid',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='workerfileshashentry',
            name='files_hash',
            field=models.TextField(default=''),
        ),
    ]
