# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackedmailentry',
            name='receiver',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='stackedmailentry',
            name='sender',
            field=models.EmailField(max_length=254),
        ),
    ]
