# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-11-24 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_auto_20160723_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stackedmailentry',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='stackedmailentry',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
