# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitrepo', '0003_gitbranchentry_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitprojectentry',
            name='fetched_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
