# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-11-24 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gitrepo', '0004_auto_20160723_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gitbranchentry',
            name='name',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='gitcommitentry',
            name='commit_hash',
            field=models.CharField(default='0000000000000000000000000000000000000000', max_length=40),
        ),
        migrations.AlterField(
            model_name='gitdiffentry',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='gitprojectentry',
            name='name',
            field=models.CharField(default='default-name', max_length=50),
        ),
        migrations.AlterField(
            model_name='gituserentry',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
