# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-11-24 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluesteel', '0008_bluesteelprojectentry_git_project_folder_search_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluesteellayoutentry',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='bluesteelprojectentry',
            name='git_project_folder_search_path',
            field=models.CharField(default='.', max_length=255),
        ),
        migrations.AlterField(
            model_name='bluesteelprojectentry',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
